### ISSUE TITLE
Do you have a community mesh network in your state?

### ISSUE THREAD

**Issue by Blkzer0** [RazzyT/hydranet#1]
i have one in my state, check out the site, it'll give you an insight as to how we connect everything. nycmesh.net/map/

**Comment by RazzyT** [comment]
We could look into connecting the existing mesh networks into Hydranet.

**Comment by RazzyT** [comment]
But other than that I believe every state has at least one mesh net. Except for Arkansas. nobody likes Arkansas. JK they might have one Idk.
